name: .NET CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET 8 SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Build CoreEngine
      working-directory: ./CoreEngine
      run: |
        dotnet restore
        dotnet build --configuration Release

    - name: Build MainApp
      working-directory: ./MainApp
      run: |
        dotnet restore
        dotnet build --configuration Release

    # NEW: Create portable EXE
    - name: Publish Standalone Game
      working-directory: ./MainApp
      run: dotnet publish -c Release -r win-x64 --self-contained true -o published/

    # NEW: Auto-release
    - name: Upload to GitHub Releases
      uses: softprops/action-gh-release@v1
      if: github.ref == 'refs/heads/master'
      with:
        files: |
          MainApp/published/**/*.exe
          MainApp/published/**/*.dll
        tag_name: latest
        body: Automated game build - ${{ github.sha }}